
name: Nightly unit tests

on:
  schedule:
    - cron: '*/1 * * * *'
    # - cron:  '20 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Setup
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          ~/.dts/
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      
    - name: Install dependencies
      run: npm i 
    - name: run unit tests 
      run: jest --detectOpenHandles  --silent
